/* ===========================================================================
* @path $(IPNCPATH)\include
*
* @desc
* .
* Copyright (c) Appro Photoelectron Inc.  2008
*
* Use of this software is controlled by the terms and conditions found
* in the license agreement under which this software has been supplied
*
* =========================================================================== */
/**
* @file Msg_Def.h
* @brief Definition of message command, message key, and message type.
*/
#ifndef __MSG_H__
#define __MSG_H__

#if defined (__cplusplus)
extern "C" {
#endif

#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/msg.h>
#include "ipnc_feature.h"
#include <System_Call_Msg_Def.h>			
#include <patrol_util.h>

/* Codec server */
/**
* @defgroup UTILITY Utility API

* This contains kinds of API  for communicating.
* @{
*/

/* OVERLAY_IMAGE_FEATURE - Dean - 20130709 - Begin */
#if 1//OVERLAY_IMAGE_FEATURE
typedef struct _OverlayImagePrm{
	int Enable;
	int ImageType;
	int Left;
	int Top;
}OverlayImagePrm;
#endif
/* OVERLAY_IMAGE_FEATURE - Dean - 20130709 - End */

#define SCHEDULE_NUM       10
typedef struct _EventPrm{
	int Enable[SCHEDULE_NUM];
	int TriggerTimeGap[SCHEDULE_NUM];
}EventPrm;

/* TAMPER_FEATURE - Dean - 20131007 - Begin */
#if 1 //TAMPER_FEATURE
typedef struct _TamperPrm{
	unsigned char Enable;
	unsigned char  Sensitivity;
	unsigned int DetectDuration;
//	unsigned int TriggerGap;
	unsigned int FocusValue;
}TamperPrm;
#endif
/* TAMPER_FEATURE - Dean - 20131007 - End */
/* PRIVACY_MASK_FEATURE - Dean - 20130801 - Begin */
#if 1 //PRIVACY_MASK_FEATURE
#define PRIVACY_MASK_ZONE_MAX 5
#define PRIVACY_MASK_ZONE_TITLE_LEN	16
typedef struct _PrivacyMaskPrm{
	int Enable;
	int ZoneEnable[PRIVACY_MASK_ZONE_MAX];
	int ZoneColor[PRIVACY_MASK_ZONE_MAX];
	int Left[PRIVACY_MASK_ZONE_MAX];
	int Top[PRIVACY_MASK_ZONE_MAX];
	int Right[PRIVACY_MASK_ZONE_MAX];
	int Bottom[PRIVACY_MASK_ZONE_MAX];
	char Title[PRIVACY_MASK_ZONE_MAX][PRIVACY_MASK_ZONE_TITLE_LEN];
}PrivacyMaskPrm;
#endif
/* PRIVACY_MASK_FEATURE - Dean - 20130801 - End */

/*add the PTZ structure for Geo's PTZ by frank*/
#if IPNCPTZ_FEATURE
typedef struct _PTZPrm{
	int cmd;//command, PAN,TILT....
	int x;
	int y;
}PTZPrm;
	
#endif
enum {
	MSG_CMD_START = 0,
	MSG_CMD_GET_MEM,
	MSG_CMD_QUIT,
	MSG_CMD_SET_MEM,
	MSG_CMD_PRINT_MEM,
	MSG_CMD_GET_CUR_FRAME,
	MSG_CMD_LOCK_FRAME,
	MSG_CMD_UNLOCK_FRAME,
	MSG_CMD_GET_MEDIA_INFO,
	MSG_CMD_GET_VOL,
	MSG_CMD_GET_NEW_FRAME,
	MSG_CMD_GET_AND_LOCK_IFRAME,
	MSG_CMD_SET_DAY_NIGHT,
	MSG_CMD_SET_WHITE_BALANCE,
	MSG_CMD_SET_BACKLIGHT,
	MSG_CMD_SET_BRIGHTNESS,
	MSG_CMD_SET_CONTRAST,
	MSG_CMD_SET_SATURATION,
	MSG_CMD_SET_SHARPNESS,
	MSG_CMD_SET_AAC_BITRATE,
	MSG_CMD_SET_MAIN_DEWARPMODE,
	MSG_CMD_SET_3rd_DEWARPMODE,
	MSG_CMD_SET_RESOLUTION1,
	MSG_CMD_SET_RESOLUTION2,
	MSG_CMD_SET_RESOLUTION3,
	MSG_CMD_SET_RESOLUTION4,
	
	MSG_CMD_SET_BITRATE1,
	MSG_CMD_SET_BITRATE2,
	MSG_CMD_SET_BITRATE3,
	MSG_CMD_SET_JPEG_QUALITY,
	//MSG_CMD_SET_ROTATION, //RS,DC
	MSG_CMD_SET_FDETECT,
	MSG_CMD_SET_MIRROR,
	MSG_CMD_SET_OSDWINDOW,
	//MSG_CMD_SET_DEMOCFG, //RS,DC
	MSG_CMD_SET_M41_FRAMERATE,
	MSG_CMD_SET_M42_FRAMERATE,
	MSG_CMD_SET_JPG_FRAMERATE,
	MSG_CMD_SET_FRAMERATE1,
	MSG_CMD_SET_FRAMERATE2,
	MSG_CMD_SET_FRAMERATE3,
	MSG_CMD_SET_FRAMERATE4,
	MSG_CMD_SWITCH_2A,
	MSG_CMD_TYPE_2A,
	MSG_CMD_2A_PRIORITY,
	MSG_CMD_SET_TV_SYSTEM,
	#if BINNING_FEATURE
	MSG_CMD_SET_BINNING_SKIP,
	#endif
	MSG_CMD_SET_TSTAMP,
	MSG_CMD_SET_DATETIMEPRM,
	MSG_CMD_PTZ,
	MSG_CMD_GET_PTZ_PRESET, 
	MSG_CMD_GET_PTZ_PATROL, 
	MSG_CMD_GET_PTZ_STATUS,
	MSG_CMD_SET_PTZ_PRESET,	
	MSG_CMD_SET_PTZ_PATROL,	
	//MSG_CMD_INIT_PTZ, //RS,DC
	MSG_CMD_SET_MOTION_BLOCK,
	MSG_CMD_SET_MOTION,
	MSG_CMD_SET_MOTION_CENABLE,
	MSG_CMD_SET_MOTION_LEVEL,
	MSG_CMD_SET_MOTION_CVALUE,
	MSG_CMD_SET_ROICFG,
	MSG_CMD_SET_OVERLAY_IMAGE,				/* OVERLAY_IMAGE_FEATURE - Dean - 20130709 */
	MSG_CMD_SET_TAMPER,						/* TAMPER_FEATURE - Dean - 20131007 */
	MSG_CMD_SET_EVENT, 						/* TAMPER_FEATURE Event - Dean - 20131007 */
	MSG_CMD_SET_OSDTEXT_EN,
	MSG_CMD_SET_HIST_EN,
	MSG_CMD_SET_OSDLOGO_EN,
	MSG_CMD_SET_OSDTEXT,
	MSG_CMD_SET_OSDPRM1,
	MSG_CMD_SET_OSDPRM2,
	MSG_CMD_SET_OSDPRM3,
	MSG_CMD_SET_LOCALDISPLAY,
	MSG_CMD_SET_CLICKNAME,
	MSG_CMD_SET_CLICKSTORAGE,
	MSG_CMD_SET_ROIPRM1,
	MSG_CMD_SET_ROIPRM2,
	MSG_CMD_SET_ROIPRM3,
	MSG_CMD_SET_ADVCODECPRM1,
	MSG_CMD_SET_ADVCODECPRM2,
	MSG_CMD_SET_ADVCODECPRM3,
	MSG_CMD_SET_OSDENABLE,
	MSG_CMD_SET_IFRAME,
	MSG_CMD_SET_VNFSTATUS1,
	MSG_CMD_SET_VNFSTATUS2,
	MSG_CMD_SET_VNFSTATUS3,
	MSG_CMD_SET_AUDIO_ALARM_LEVEL,
	MSG_CMD_SET_AUDIO_ALARM_FLAG,
	MSG_CMD_SET_DYNRANGE,
	MSG_CMD_POLLING,
	MSG_CMD_SET_WDTRESET,
	MSG_CMD_SET_LINEAR_WAR,
	MSG_CMD_SET_FLICKER_DETECT,

	/* DMVA Specific */
	MSG_CMD_SET_DMVAENABLE,
    MSG_CMD_SET_DMVAALGOFRAMERATE,
    MSG_CMD_SET_DMVAALGODETECTFREQ,
    MSG_CMD_SET_DMVAEVTRECORDENABLE,
    MSG_CMD_SET_DMVASMETATRACKERENABLE,
	/* DMVA TZ Specific */
	MSG_CMD_SET_DMVA_TZ,
	/* DMVA MAIN Specific */
	MSG_CMD_SET_DMVA_MAIN,
	/* DMVA CTD Specific */
	MSG_CMD_SET_DMVA_CTD,
	/* DMVA OC Specific */
	MSG_CMD_SET_DMVA_OC,
	/* DMVA SMETA Specific */
	MSG_CMD_SET_DMVA_SMETA,
	/* DMVA IMD Specific */
	MSG_CMD_SET_DMVA_IMD,

	/* DMVA Enc Roi Enable */
	MSG_CMD_SET_DMVA_ENCROI_ENABLE,

	//MSG_CMD_SET_OVERLAY_IMAGE,				/* OVERLAY_IMAGE_FEATURE - Dean - 20130709 */
	MSG_CMD_SET_PRIVACY_MASK,				/* PRIVACY_MASK_FEATURE - Dean - 20130801 */
	//MSG_CMD_SET_TAMPER,						/* TAMPER_FEATURE - Dean - 20131007 */
	MSG_CMD_SET_M41_ADV_FEATURE,
	MSG_CMD_SET_M42_ADV_FEATURE,
	MSG_CMD_SET_JPG_ADV_FEATURE,
	MSG_CMD_SET_M41_GOP,
	MSG_CMD_SET_IRIS_MODE, // kenny chiu 20110512
	MSG_CMD_SET_WDR_MODE, // Cato@20120508
//	MSG_CMD_SET_IRCUT_STATUS, // kenny chiu 20110516
	MSG_CMD_SET_EXPOSUREMODE,
	MSG_CMD_SET_EXPOSUREVALUE,
	MSG_CMD_SET_EXPOSUREVALUE1,
	MSG_CMD_SET_AGC,
	MSG_CMD_SET_AGC_MIN,
	MSG_CMD_SET_AGC1,
	MSG_CMD_SET_AGC_MIN1,
	MSG_CMD_SET_SHUTTER_TIME,
	MSG_CMD_SET_SHUTTER_TIME_MIN,
	MSG_CMD_SET_SHUTTER_TIME1,
	MSG_CMD_SET_SHUTTER_TIME_MIN1,
	MSG_CMD_SET_FLICKERLESS_MODE,
	MSG_CMD_SET_COLORBAR,
	MSG_CMD_SET_AEWB_RESET,
	MSG_CMD_SET_MOBILE_FRAMERATE,
	MSG_CMD_SET_MOBILE_RATECONTROL,
	MSG_CMD_SET_MOBILE_QUALITY,
	MSG_CMD_SET_MOBILE_BITRATE,
	MSG_CMD_SET_AUTOIRIS_ACTION,
	MSG_CMD_SET_TVOUT_ENABLE,
	MSG_CMD_SET_AUDIO_BROADCAST_PORT,
    MSG_CMD_SET_EWDR_MODE, //Add by Kenny Chiu 20131210
    MSG_CMD_SET_AUDIO_INVOLUME, // Add by Joseph 20140516
	MSG_CMD_END
};

/* system control */
/**
* @brief Commands used to control system server.
*/
enum {
	SYS_MSG_GET_DHCP_EN, ///< Get DHCP status.
	SYS_MSG_GET_HTTP_PORT, ///< Get http port.
	SYS_MSG_SET_NETMASK, ///< Set new netmask of IP netcam.
	SYS_MSG_GET_SNTP_FQDN, ///< Get SNTP FQDN.
	SYS_MSG_SET_TIME, ///< Set system time.
	SYS_MSG_SET_TIMEFORMAT, ///< Set display time format.
	SYS_MSG_GET_DEVICE_TYPE, ///< Get device type.
	SYS_MSG_GET_TITLE, ///< Get IP netcam title.
	SYS_MSG_GET_REGUSR, ///< Get IP netcam title.
	SYS_MSG_GET_OSDTEXT, ///< Get IP netcam title.
	SYS_MSG_GET_MAC, ///< Get ethernet MAC address.
	SYS_MSG_GET_IP, ///< Get IP netcam IP address.
	SYS_MSG_GET_GATEWAY, ///< Get IP netcam gateway.
	SYS_MSG_GET_NETMASK, ///< Get IP netcam netmask.
	SYS_MSG_GET_FTP_SERVER_IP, ///< Get FTP FQDN.
	SYS_MSG_GET_FTP_USERNAME, ///< Get FTP user name.
	SYS_MSG_GET_FTP_PASSWORD, ///< Get FTP user password.
	SYS_MSG_GET_FTP_FOLDNAME, ///< Get FTP foleder.
	SYS_MSG_GET_FTP_IMAGEAMOUNT, ///< Get JPEG count at each FTP connection.
	SYS_MSG_GET_FTP_PID, ///< Get FTP process ID.
	SYS_MSG_GET_FTP_PORT, ///< Get FTP connection port.
	SYS_MSG_GET_SMTP_SERVER_IP, ///< Get SMTP FQDN.
	SYS_MSG_GET_SMTP_SERVER_PORT, ///< Get SMTP PORT.
	SYS_MSG_GET_SMTP_AUTHENTICATION, ///< See if use authentication to send e-mail.
	SYS_MSG_GET_SMTP_USERNAME, ///< Get SMTP user name.
	SYS_MSG_GET_SMTP_PASSWORD, ///< Get SMTP password.
	SYS_MSG_GET_SMTP_SENDER_EMAIL_ADDRESS, ///< Get sender e-mail address.
	SYS_MSG_GET_SMTP_RECEIVER_EMAIL_ADDRESS, ///< Get receiver e-mail address.
	SYS_MSG_GET_SMTP_CC, ///< Get e-mail CC.
	SYS_MSG_GET_SMTP_SUBJECT, ///< Get e-mail subject.
	SYS_MSG_GET_SMTP_TEXT, ///< Get e-mail text.
	SYS_MSG_GET_SMTP_ATTACHMENTS, ///< Get e-mail JPEG attachments.
	SYS_MSG_GET_SMTP_VIEW, ///< Get e-mail style.
	SYS_MSG_GET_DHCP_CONFIG, ///< Get DHCP status.
	//SYS_MSG_GET_UPNP_PORT,
	SYS_MSG_SET_IP, ///< Set static IP address.
	SYS_MSG_SET_TITLE, ///< Set IP netcam title.
	SYS_MSG_SET_REGUSR, ///< Set IP netcam title.
	SYS_MSG_SET_OSDTEXT, ///< Set IP netcam title.
	SYS_MSG_SET_GATEWAY, ///< Set gateway in static IP mode.
	SYS_MSG_SET_DHCPC_ENABLE, ///< Set DHCP enable.
	SYS_MSG_SET_FTP_FQDN, ///< Set FTP FQDN.
	SYS_MSG_SET_FTP_USERNAME, ///< Set FTP username.
	SYS_MSG_SET_FTP_PASSWORD, ///< Set FTP password.
	SYS_MSG_SET_FTP_FOLDNAME, ///< Set FTP folder.
	SYS_MSG_SET_FTP_IMAGEAMOUNT, ///< Set JPEG count at each FTP connection.
	SYS_MSG_SET_FTP_PID, ///< Save FTP process ID.
	SYS_MSG_SET_FTP_PORT, ///< Set FTP port.
	SYS_MSG_SET_SMTP_SERVER_IP, ///< Set SMTP FQDN.
	SYS_MSG_SET_SMTP_SERVER_PORT, ///< Set SMTP PORT.
	SYS_MSG_SET_SMTP_AUTHENTICATION, ///< Let IP netcam use authentication to send e-mail or not.
	SYS_MSG_SET_SMTP_USERNAME, ///< Set SMTP user name.
	SYS_MSG_SET_SMTP_PASSWORD, ///< Set SMTP password.
	SYS_MSG_SET_SMTP_SENDER_EMAIL_ADDRESS, ///< Set sender e-mail address.
	SYS_MSG_SET_SMTP_RECEIVER_EMAIL_ADDRESS, ///< Set receiver e-mail address.
	SYS_MSG_SET_SMTP_CC, ///< Set e-mail CC.
	SYS_MSG_SET_SMTP_SUBJECT, ///< Set e-mail subject.
	SYS_MSG_SET_SMTP_TEXT, ///< Set e-mail text.
	SYS_MSG_SET_SMTP_ATTACHMENTS, ///< Set e-mail JPEG attachments.
	SYS_MSG_SET_SMTP_VIEW, ///< Set e-mail style.
	SYS_MSG_GET_DNS, ///< Get DNS address.
	SYS_MSG_SET_DNS, ///< Set DNS address.
	SYS_MSG_SET_DNS2, ///< Set DNS address.		/* Airlive IP Finder - Dean - 20120626 */
	SYS_MSG_SET_HOSTNAME,    ///<set hostname.
	SYS_MSG_SET_SNTP_SERVER_IP, ///< Set SNTP FQDN.
	SYS_MSG_SET_COLOR_BAR, ///< Test Pattern (color bar)
	SYS_MSG_SET_EXPOSUREMODE,
	SYS_MSG_SET_EXPOSUREVALUE,
	SYS_MSG_SET_EXPOSUREVALUE1,
	SYS_MSG_SET_AGC,
	SYS_MSG_SET_AGC_MIN,
	SYS_MSG_SET_AGC1,
	SYS_MSG_SET_AGC_MIN1,
	SYS_MSG_SET_SHUTTER_TIME,
	SYS_MSG_SET_SHUTTER_TIME_MIN,
	SYS_MSG_SET_SHUTTER_TIME1,
	SYS_MSG_SET_SHUTTER_TIME_MIN1,
	SYS_MSG_SET_FLICKERLESS_MODE,
//SYS_MSG_SET_ROTATION, ///< Set Rotation.
	SYS_MSG_SET_ADVMODE,
	SYS_MSG_SET_M41SFEATURE,
	SYS_MSG_SET_M42SFEATURE, ///< Set Noise Filter.
	SYS_MSG_SET_JPGSFEATURE,
	SYS_MSG_SET_IRIS_MODE,	//Set iris mode of IP netcam ; kenny chiu 20110512
	SYS_MSG_SET_WDR_MODE,
	SYS_MSG_SET_DEMOCFG,
	SYS_MSG_SET_OSDWIN,
	SYS_MSG_SET_OSDWINNUM,
	SYS_MSG_SET_OSDSTREAM,
	SYS_MSG_SET_VIDEO_CODEC,
	SYS_MSG_SET_VIDEOCODEC_MODE, ///< Set video codec mode. This operation will take several time.
	SYS_MSG_SET_SCHEDULE, ///< Set user define schedule.
	SYS_MSG_DEL_SCHEDULE, ///< Delete all exist schedule.
	SYS_MSG_SET_VIDEO_MODE,
	SYS_MSG_SET_IMAGE_FORMAT,
	SYS_MSG_SET_MAIN_DEWARPMODE,	
	SYS_MSG_SET_3rd_DEWARPMODE,	
	
	SYS_MSG_SET_RESOLUTION, ///< Set JPEG resolution.
	SYS_MSG_SET_MPEG4_RES, ///< Set MPEG1 resolution.
	SYS_MSG_SET_MPEG42_RES, ///< Set MPEG2 resolution.
	SYS_MSG_SET_MPEG43_RES, ///< Set MPEG2 resolution.
	SYS_MSG_SET_MPEG4_QUALITY, ///By Larry
    SYS_MSG_SET_LOSTALARM, ///< Enable ethernet lost alarm or not.
	SYS_MSG_SET_SDAENABLE, ///< Enable save file to SD card when alarm happen or not.
	SYS_MSG_SET_FTPAENABLE, ///< Enable send file to FTP server when alarm happen or not.
	SYS_MSG_SET_SMTPAENABLE, ///< Enable send file to SMTP server when alarm happen or not.
	SYS_MSG_SET_ALARMDURATION, ///< Set how long will one alarm last.
	SYS_MSG_SET_AVIDURATION, ///< Set length of one AVI file(in seconds).
	SYS_MSG_SET_AVIFORMAT, ///< Set format of AVI file.
	SYS_MSG_SET_FTPFILEFORMAT, ///< Sent which kind of files to FTP.
	SYS_MSG_SET_SDFILEFORMAT, ///< Save which kind of files to SD card.
	SYS_MSG_SET_ATTFILEFORMAT, ///< Sent which kind of files to SMTP.
	SYS_MSG_SET_ASMTPATTACH,
	SYS_MSG_SET_FTP_RFTPENABLE, ///< Enable send file to FTP server at schedule.
	SYS_MSG_SET_SD_REENABLE, ///< Enable save file to SD card at schedule.
	SYS_MSG_SET_IMAGE_SOURCE, ///< Select NTSC/PAL mode.
	SYS_MSG_SET_TVCABLE, ///< Set TV cable connect or not.
	/* Live Video Page */
	SYS_MSG_SET_CLICK_SNAP_FILENAME,
	SYS_MSG_SET_CLICK_SNAP_STORAGE,
	/* Video & Image */
	SYS_MSG_SET_VIDEOCODEC_COMBO,
	SYS_MSG_SET_VIDEOCODEC_RES, ///< Set video resolution. This operation will take several time.
	SYS_MSG_SET_MPEG41_BITRATE, ///< Set MPEG1 bitrate.
	SYS_MSG_SET_MPEG42_BITRATE, ///< Set MPEG2 bitrate.
	SYS_MSG_SET_MPEG43_BITRATE, 	
	SYS_MSG_SET_MPEG41_FRAMERATE, ///< Set MPEG1 frame rate.(109)
	SYS_MSG_SET_MPEG42_FRAMERATE, ///< Set MPEG2 frame rate.(110)
	SYS_MSG_SET_MPEG43_FRAMERATE, ///< Set MPEG2 frame rate.
	SYS_MSG_SET_JPEG_QUALITY, ///< Set JPEG encode quality.
	SYS_MSG_SET_M41_GOP,
	SYS_MSG_SET_FRAMERATE1, ///< Set MPEG1 frame rate.
	SYS_MSG_SET_FRAMERATE2, ///< Set MPEG2 frame rate.
	SYS_MSG_SET_FRAMERATE3, ///< Set JPEG frame rate.
	SYS_MSG_SET_RATE_CONTROL1,
	SYS_MSG_SET_RATE_CONTROL2,
	SYS_MSG_SET_MOBILE_MODE,
	SYS_MSG_SET_MOBILE_RATECONTROL,
	SYS_MSG_SET_MOBILE_FRAMERATE,
	SYS_MSG_SET_MOBILE_QUALITY,
	SYS_MSG_SET_MOBILE_BITRATE,
	SYS_MSG_SET_DATE_STAMP_ENABLE1,
	SYS_MSG_SET_DATE_STAMP_ENABLE2,
	SYS_MSG_SET_DATE_STAMP_ENABLE3,
	SYS_MSG_SET_TIME_STAMP_ENABLE1,
	SYS_MSG_SET_TIME_STAMP_ENABLE2,
	SYS_MSG_SET_TIME_STAMP_ENABLE3,
	SYS_MSG_SET_LOGO_ENABLE1,
	SYS_MSG_SET_LOGO_ENABLE2,
	SYS_MSG_SET_LOGO_ENABLE3,
	SYS_MSG_SET_LOGO_POSITION1,
	SYS_MSG_SET_LOGO_POSITION2,
	SYS_MSG_SET_LOGO_POSITION3,
	SYS_MSG_SET_TEXT_ENABLE1,
	SYS_MSG_SET_TEXT_ENABLE2,
	SYS_MSG_SET_TEXT_ENABLE3,
	SYS_MSG_SET_TEXT_POSITION1,
	SYS_MSG_SET_TEXT_POSITION2,
	SYS_MSG_SET_TEXT_POSITION3,
	SYS_MSG_SET_OVERLAY_TEXT1,
	SYS_MSG_SET_OVERLAY_TEXT2,
	SYS_MSG_SET_OVERLAY_TEXT3,
    SYS_MSG_SET_DETAIL_INFO1,
    SYS_MSG_SET_DETAIL_INFO2,
    SYS_MSG_SET_DETAIL_INFO3,

	//SYS_MSG_START_RESTART_ALL,

	SYS_MSG_SET_PRIVACY_MASK_CONFIG,
	SYS_MSG_GET_PRIVACY_MASK_CONFIG,

	//SYS_MSG_SET_TAMPER_CONFIG,
	//SYS_MSG_GET_TAMPER_CONFIG,

	SYS_MSG_SET_ENCRYPT_VIDEO,
	SYS_MSG_SET_LOCAL_DISPLAY,
	SYS_MSG_SET_MIRROR,
	SYS_MSG_SET_ENCRYPTION,

	/* Video advanced */
	SYS_MSG_SET_IPRATIO1,
	SYS_MSG_SET_IPRATIO2,
	SYS_MSG_SET_IPRATIO3,
	SYS_MSG_SET_FORCE_IFRAME1,
	SYS_MSG_SET_FORCE_IFRAME2,
	SYS_MSG_SET_FORCE_IFRAME3,
	SYS_MSG_SET_QPINIT1,
	SYS_MSG_SET_QPINIT2,
	SYS_MSG_SET_QPINIT3,
	SYS_MSG_SET_QPMIN1,
	SYS_MSG_SET_QPMIN2,
	SYS_MSG_SET_QPMIN3,
	SYS_MSG_SET_QPMAX1,
	SYS_MSG_SET_QPMAX2,
	SYS_MSG_SET_QPMAX3,
	SYS_MSG_SET_MECONFIG1,
	SYS_MSG_SET_MECONFIG2,
	SYS_MSG_SET_MECONFIG3,
	SYS_MSG_SET_PACKET_SIZE1,
	SYS_MSG_SET_PACKET_SIZE2,
	SYS_MSG_SET_PACKET_SIZE3,
	SYS_MSG_SET_ROI_ENABLE1,
	SYS_MSG_SET_ROI_ENABLE2,
	SYS_MSG_SET_ROI_ENABLE3,
	SYS_MSG_SET_STR1X1,
	SYS_MSG_SET_STR1Y1,
	SYS_MSG_SET_STR1W1,
	SYS_MSG_SET_STR1H1,
	SYS_MSG_SET_STR1X2,
	SYS_MSG_SET_STR1Y2,
	SYS_MSG_SET_STR1W2,
	SYS_MSG_SET_STR1H2,
	SYS_MSG_SET_STR1X3,
	SYS_MSG_SET_STR1Y3,
	SYS_MSG_SET_STR1W3,
	SYS_MSG_SET_STR1H3,
	SYS_MSG_SET_STR2X1,
	SYS_MSG_SET_STR2Y1,
	SYS_MSG_SET_STR2W1,
	SYS_MSG_SET_STR2H1,
	SYS_MSG_SET_STR2X2,
	SYS_MSG_SET_STR2Y2,
	SYS_MSG_SET_STR2W2,
	SYS_MSG_SET_STR2H2,
	SYS_MSG_SET_STR2X3,
	SYS_MSG_SET_STR2Y3,
	SYS_MSG_SET_STR2W3,
	SYS_MSG_SET_STR2H3,
	SYS_MSG_SET_STR3X1,
	SYS_MSG_SET_STR3Y1,
	SYS_MSG_SET_STR3W1,
	SYS_MSG_SET_STR3H1,
	SYS_MSG_SET_STR3X2,
	SYS_MSG_SET_STR3Y2,
	SYS_MSG_SET_STR3W2,
	SYS_MSG_SET_STR3H2,
	SYS_MSG_SET_STR3X3,
	SYS_MSG_SET_STR3Y3,
	SYS_MSG_SET_STR3W3,
	SYS_MSG_SET_STR3H3,
	/* Video Analytics */
	SYS_MSG_SET_MOTIONENABLE, ///< Enable motion detection or not.
	SYS_MSG_SET_MOTIONCENABLE, ///< Use customer define or normal mode.
	SYS_MSG_SET_MOTIONLEVEL, ///< Set motion level in normal mode.
	SYS_MSG_SET_MOTIONCVALUE, ///< Set customer value at customer mode.
	SYS_MSG_SET_MOTIONBLOCK, ///< Define motion blocks.
	SYS_MSG_SET_FDETECT,
	SYS_MSG_SET_FDX,
	SYS_MSG_SET_FDY,
	SYS_MSG_SET_FDW,
	SYS_MSG_SET_FDH,
	SYS_MSG_SET_FDCONF_LEVEL,
	SYS_MSG_SET_FD_DIRECTION,
	SYS_MSG_SET_FRECOGNITION,
	SYS_MSG_SET_FRCONF_LEVEL,
	SYS_MSG_SET_FR_DATABASE,
	SYS_MSG_SET_PRIVACY_MASK,
	SYS_MSG_SET_MASK_OPTIONS,
	/* Camera Page */
	SYS_MSG_SET_BRIGHTNESS, ///< Set brightness.
	SYS_MSG_SET_CONTRAST, ///< Set contrast.
	SYS_MSG_SET_SATURATION, ///< Set saturation.
	SYS_MSG_SET_SHARPNESS, ///< Set sharpness.
	SYS_MSG_SET_CLEARSYSLOG, ///< Clear System Log
	SYS_MSG_SET_CLEARACCESSLOG, ///< Clear Access Log
	SYS_MSG_SET_BLC,
	SYS_MSG_SET_BACKLIGHT, ///< Set backlight mode of IP netcam.
	SYS_MSG_SET_DYNRANGE,
	SYS_MSG_SET_DYNRANGESTR,
	SYS_MSG_SET_WHITE_BALANCE, ///< Set whitebalance moe of IP netcam.
	SYS_MSG_SET_DAY_NIGHT, ///< Set day/night mode of IP netcam.
	SYS_MSG_SET_HISTOGRAM,
	SYS_MSG_SET_VSTAB,
	SYS_MSG_SET_LDC,
	SYS_MSG_SET_BINNING, ///< Set binning mode.
	SYS_MSG_SET_2A_SWITCH,
	SYS_MSG_SET_2A_TYPE,
	SYS_MSG_SET_MAXEXPOSURE, ///< Set TV cable connect or not.
	SYS_MSG_SET_MAXGAIN, ///< Set TV cable connect or not.
	SYS_MSG_SET_EXPPRIORITY,
	SYS_MSG_SET_SNF,
	SYS_MSG_SET_TNF,
    /* Audio Page */
	SYS_MSG_SET_AUDIOENABLE, ///< Enable audio send to web site or not.
	SYS_MSG_SET_AUDIOMODE,
	SYS_MSG_SET_AUDIOINVOLUME, ///< Set alarm audio volume
	SYS_MSG_SET_AUDIO_ENCODE,
	SYS_MSG_SET_AUDIO_SAMPLERATE,
	SYS_MSG_SET_AUDIO_BITRATE,
	SYS_MSG_SET_AUDIO_ALARMLEVEL,
	SYS_MSG_SET_SPEAKER_ENABLE,
	SYS_MSG_SET_AUDIOOUTVOLUME,
	SYS_MSG_SET_AUDIORECEIVER_ENABLE,
	SYS_MSG_SET_AUDIOSERVER_IP,
    /* Date Time Page */
	SYS_MSG_SET_DAYLIGHT, ///< Set system time to use daylight or not.
	SYS_MSG_SET_TIMEZONE, ///< Set system time zone.
	SYS_MSG_SET_DATEFORMAT,
	SYS_MSG_SET_TSTAMPFORMAT, ///< Set timestamp format.
	SYS_MSG_SET_DATEPPOS,
	SYS_MSG_SET_TIMEPOS,
    /* Network & Port Page */
	SYS_MSG_SET_MULTICAST,///< Set Multicast fuction enable / disable.
	SYS_MSG_SET_HTTPPORT, ///< set web site port. This operation may take serveral time.
	SYS_MSG_SET_HTTPSPORT,
	SYS_MSG_SET_GIOINTYPE, ///< Set GIO input alarm triger type(high triger or low triger).
	SYS_MSG_SET_GIOOUTTYPE, ///< Set GIO output high or low.
	SYS_MSG_SET_RS485,
	/* Alarm & Storage */
	SYS_MSG_SET_ALARM_ENABLE,
	SYS_MSG_SET_AUDIOALARM,
	SYS_MSG_SET_EXT_ALARM,
	SYS_MSG_SET_ALARM_AUDIOPLAY,
	SYS_MSG_SET_ALARM_AUDIOFILE,
	SYS_MSG_SET_ALARMLOCAL,
	SYS_MSG_SET_RECORDLOCAL,
    SYS_MSG_SET_SCHEDULE_REPEAT_ENABLE,
    SYS_MSG_SET_SCHEDULE_NUM_WEEKS,
    SYS_MSG_SET_SCHEDULE_INFINITE_ENABLE,
	/* Maintainence */
	SYS_MSG_SET_DEFAULT,
	SYS_MSG_SET_REBOOT,
	SYS_MSG_SET_FACTORY_RESET,
	SYS_MSG_SET_BACKUP,
	SYS_MSG_SET_BACKUP_TO_MMC,
	SYS_MSG_SET_RESTORE,
	SYS_MSG_SET_RESTORE_FROM_MMC,
	/**********************/
	SYS_MSG_SET_RATE_CONTROL, ///< Set rate control.
	SYS_MSG_SET_JPEG_FRAMERATE, ///< Set JPEG frame rate.(108)
	SYS_MSG_SET_IMAGE_DEFAULT, ///< Set all image setting to default.
	SYS_MSG_DO_LOGIN, ///< Do user login.
	SYS_MSG_GET_USER_AUTHORITY, ///< Get user authority by name.
	SYS_MSG_ADD_USER, ///< Add/change user acount.
	SYS_MSG_DEL_USER, ///< Delete user acount.
	SYS_MSG_SET_GIOINENABLE, ///< Enable GIO input alarm or not.
	SYS_MSG_SET_GIOOUTENABLE, ///< Enable GIO ouput at alarm or not.
	SYS_MSG_SET_TSTAMPENABLE, ///< Enable timestamp or not.
	SYS_MSG_QUIT, ///< Make system server quit processing.
	SYS_MSG_IPNCPTZ, ///< Contorl PTZ.
	SYS_MSG_INIT_IPNCPTZ,///Init PTZ(4X).
#if 1 // SD_FEATURE
	SYS_MSG_SD_FORMAT, ///< Format SD card.
	SYS_MSG_SD_UNMOUNT, ///< Unmount SD card.
#endif
	SYS_MSG_SCHEDULE_STOP, ///< Stop schedule.
	SYS_MSG_SCHEDULE_RESUME, ///< Resume schedule.
#if 1 // SD_FEATURE
	SYS_MSG_GET_SD_FILENAME,///< Get current recording file in SD card.
#endif
	SYS_MSG_DO_BOOT_PROC,///< Tell system server to do something about boot control.
        SYS_MSG_ADD_PROFILE,  ///create onvif profile.....
        SYS_MSG_ADD_VIDEOSOURCE_CONF,        //add video source confiuration .
	SYS_MSG_SET_AUDIOSOURCE_CONF,
        SYS_MSG_SET_VIDEOSOURCE_CONF,
        SYS_MSG_SET_IMAGING_CONF,
        SYS_MSG_ADD_VIDEOENCODER_CONF,
        SYS_MSG_SET_VIDEOENCODER_CONF,
        SYS_MSG_DEL_VIDEOENCODER_CONF,
	SYS_MSG_ADD_AUDIO_SOURCE_CONF,
	SYS_MSG_ADD_AUDIO_ENCODER_CONF,
	SYS_MSG_SET_AUDIO_SOURCE_CONF,
	SYS_MSG_SET_AUDIO_ENCODER_CONF,
	SYS_MSG_DEL_AUDIO_SOURCE_CONF,
	SYS_MSG_DEL_AUDIO_ENCODER_CONF,
        SYS_MSG_DEL_PROFILE,
        SYS_MSG_SET_DIS_MODE,            //set discovery mode
        SYS_MSG_ADD_SCOPE,                //add scopes
        SYS_MSG_DEL_SCOPE,                //remove scopes
        SYS_MSG_SET_ANALYTICS,             //set video analytics
        SYS_MSG_SET_OUTPUT,             //set video output
	SYS_MSG_SET_RELAY,		//set relays
	SYS_MSG_SET_RELAY_LOGICALSTATE,
	SYS_MSG_SET_METADATA,
	SYS_MSG_ADD_METADATA,
	SYS_MSG_SET_LINEAR_WDR,
	SYS_MSG_SET_FLICKER_DETECT,

	/* Advanced DMVA System Message Parameters */
	SYS_MSG_SET_DMVAENABLE,
    SYS_MSG_SET_DMVAALGOFRAMERATE,
    SYS_MSG_SET_DMVAALGODETECTFREQ,
    SYS_MSG_SET_DMVAEVTRECORDENABLE,
    SYS_MSG_SET_DMVASMETATRACKERENABLE,
	/* DMVA TZ System Message Parameters */
    SYS_MSG_SET_DMVA_TZ_SENSITIVITY,
    SYS_MSG_SET_DMVA_TZ_PERSONMINWIDTH,
    SYS_MSG_SET_DMVA_TZ_PERSONMINHEIGHT,
    SYS_MSG_SET_DMVA_TZ_VEHICLEMINWIDTH,
    SYS_MSG_SET_DMVA_TZ_VEHICLEMINHEIGHT,
    SYS_MSG_SET_DMVA_TZ_PERSONMAXWIDTH,
    SYS_MSG_SET_DMVA_TZ_PERSONMAXHEIGHT,
    SYS_MSG_SET_DMVA_TZ_VEHICLEMAXWIDTH,
    SYS_MSG_SET_DMVA_TZ_VEHICLEMAXHEIGHT,
    SYS_MSG_SET_DMVA_TZ_DIRECTION,
    SYS_MSG_SET_DMVA_TZ_PRESENTADJUST,
    SYS_MSG_SET_DMVA_TZ_ENABLE,

  SYS_MSG_SET_DMVA_TZ_ZONE1_ROI_NUMSIDES,
  SYS_MSG_SET_DMVA_TZ_ZONE2_ROI_NUMSIDES,

  SYS_MSG_SET_DMVA_TZ_ZONE1_X01,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X02,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X03,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X04,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X05,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X06,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X07,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X08,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X09,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X10,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X11,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X12,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X13,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X14,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X15,
  SYS_MSG_SET_DMVA_TZ_ZONE1_X16,

  SYS_MSG_SET_DMVA_TZ_ZONE1_Y01,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y02,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y03,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y04,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y05,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y06,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y07,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y08,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y09,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y10,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y11,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y12,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y13,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y14,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y15,
  SYS_MSG_SET_DMVA_TZ_ZONE1_Y16,

  SYS_MSG_SET_DMVA_TZ_ZONE2_X01,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X02,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X03,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X04,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X05,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X06,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X07,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X08,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X09,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X10,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X11,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X12,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X13,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X14,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X15,
  SYS_MSG_SET_DMVA_TZ_ZONE2_X16,

  SYS_MSG_SET_DMVA_TZ_ZONE2_Y01,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y02,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y03,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y04,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y05,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y06,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y07,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y08,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y09,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y10,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y11,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y12,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y13,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y14,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y15,
  SYS_MSG_SET_DMVA_TZ_ZONE2_Y16,
  SYS_MSG_SET_DMVA_TZ_SAVE,
  SYS_MSG_SET_DMVA_TZ_LOAD,

	  /* DMVA MAIN ANALYTICS PAGE */
	  SYS_MSG_SET_DMVA_MAIN_CAMID,
	  SYS_MSG_SET_DMVA_MAIN_GETSCHEDULE,
	  SYS_MSG_SET_DMVA_MAIN_FD,
	  SYS_MSG_SET_DMVA_MAIN_CTDIMDSMETATZOC,
	  SYS_MSG_SET_DMVA_MAIN_DISPLAYOPTIONS,
	  SYS_MSG_SET_DMVA_MAIN_RECORDINGVAME,
	  SYS_MSG_SET_DMVA_MAIN_ACTIONPLAYSENDSEARCHTRASH,
	  SYS_MSG_SET_DMVA_MAIN_SELECTEVENT,
	  SYS_MSG_SET_DMVA_MAIN_ARCHIVEFLAG,
	  SYS_MSG_SET_DMVA_MAIN_EVENTTYPE,

	  SYS_MSG_SET_DMVA_MAIN_EL_START_MONTH,
	  SYS_MSG_SET_DMVA_MAIN_EL_START_DAY,
	  SYS_MSG_SET_DMVA_MAIN_EL_START_TIME,
	  SYS_MSG_SET_DMVA_MAIN_EL_END_MONTH,
	  SYS_MSG_SET_DMVA_MAIN_EL_END_DAY,
	  SYS_MSG_SET_DMVA_MAIN_EL_END_TIME,

	  SYS_MSG_SET_DMVA_MAIN_EL_TIME_STAMP_LABEL,
	  SYS_MSG_SET_DMVA_MAIN_EL_EVENT_DETAILS_LABEL,

	  /* DMVA ADVANCED SETTINGS PAGE */
	  SYS_MSG_SET_DMVA_ADVANCED_OBJECTMETADATA,
	  SYS_MSG_SET_DMVA_ADVANCED_OVLPROPFONTTYPE,
	  SYS_MSG_SET_DMVA_ADVANCED_OVLPROPFONTSIZE,
	  SYS_MSG_SET_DMVA_ADVANCED_OVLPROPFONTCOLOR,
	  SYS_MSG_SET_DMVA_ADVANCED_OVLPROPBOXCOLOR,
	  SYS_MSG_SET_DMVA_ADVANCED_OVLPROPCENTROIDCOLOR,
	  SYS_MSG_SET_DMVA_ADVANCED_OVLPROPACTIVEZONECOLOR,
	  SYS_MSG_SET_DMVA_ADVANCED_OVLPROPINACTIVEZONECOLOR,
	  SYS_MSG_SET_DMVA_ADVANCED_OVLPROPVELOCITYCOLOR,
	  SYS_MSG_SET_DMVA_ADVANCED_ENVPROFILELOAD,
	  SYS_MSG_SET_DMVA_ADVANCED_ENVPROFILESTORE,
	  SYS_MSG_SET_DMVA_ADVANCED_ENVPROFILECLEAR,
	  SYS_MSG_SET_DMVA_ADVANCED_ENVPROFILESTATE,
	  SYS_MSG_SET_DMVA_ADVANCED_ENVPROFILEDESC,

	  /* DMVA event delete */
	  SYS_MSG_SET_DMVA_EVENT_DELETE_INDEX,
	  SYS_MSG_SET_DMVA_EVENT_DELETE_START_INDEX,
	  SYS_MSG_SET_DMVA_EVENT_DELETE_END_INDEX,
	  SYS_MSG_SET_DMVA_EVENT_DELETE_ALL,

	  /* DMVA CTD PAGE */
	  SYS_MSG_SET_DMVA_CTD_ENV1,
	  SYS_MSG_SET_DMVA_CTD_ENV2,
	  SYS_MSG_SET_DMVA_CTD_SENSITIVITY,
	  SYS_MSG_SET_DMVA_CTD_RESETTIME,

	  /* DMVA OC PAGE */
	  SYS_MSG_SET_DMVA_OC_SENSITIVITY,
	  SYS_MSG_SET_DMVA_OC_OBJECTWIDTH,
	  SYS_MSG_SET_DMVA_OC_OBJECTHEIGHT,
	  SYS_MSG_SET_DMVA_OC_DIRECTION,
	  SYS_MSG_SET_DMVA_OC_ENABLE,
	  SYS_MSG_SET_DMVA_OC_LEFTRIGHT,
	  SYS_MSG_SET_DMVA_OC_TOPBOTTOM,
      SYS_MSG_SET_DMVA_OC_SAVE,
      SYS_MSG_SET_DMVA_OC_LOAD,


	  /* DMVA SMETA PAGE */
	  SYS_MSG_SET_DMVA_SMETA_SENSITIVITY,
	  SYS_MSG_SET_DMVA_SMETA_ENABLESTREAMINGDATA,
	  SYS_MSG_SET_DMVA_SMETA_STREAMBB,
	  SYS_MSG_SET_DMVA_SMETA_STREAMVELOCITY,
	  SYS_MSG_SET_DMVA_SMETA_STREAMHISTOGRAM,
	  SYS_MSG_SET_DMVA_SMETA_STREAMMOMENTS,
	  SYS_MSG_SET_DMVA_SMETA_PRESENTADJUST,
	  SYS_MSG_SET_DMVA_SMETA_PERSONMINWIDTH,
	  SYS_MSG_SET_DMVA_SMETA_PERSONMINHEIGHT,
	  SYS_MSG_SET_DMVA_SMETA_VEHICLEMINWIDTH,
	  SYS_MSG_SET_DMVA_SMETA_VEHICLEMINHEIGHT,
	  SYS_MSG_SET_DMVA_SMETA_PERSONMAXWIDTH,
	  SYS_MSG_SET_DMVA_SMETA_PERSONMAXHEIGHT,
	  SYS_MSG_SET_DMVA_SMETA_VEHICLEMAXWIDTH,
	  SYS_MSG_SET_DMVA_SMETA_VEHICLEMAXHEIGHT,
	  SYS_MSG_SET_DMVA_SMETA_NUMZONES,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_ROI_NUMSIDES,

  SYS_MSG_SET_DMVA_SMETA_ZONE1_X01,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X02,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X03,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X04,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X05,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X06,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X07,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X08,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X09,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X10,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X11,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X12,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X13,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X14,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X15,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_X16,

  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y01,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y02,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y03,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y04,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y05,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y06,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y07,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y08,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y09,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y10,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y11,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y12,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y13,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y14,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y15,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_Y16,
  SYS_MSG_SET_DMVA_SMETA_ZONE1_LABEL,
  SYS_MSG_SET_DMVA_SMETA_SAVE,
  SYS_MSG_SET_DMVA_SMETA_LOAD,

	  /* DMVA IMD PAGE */
	  SYS_MSG_SET_DMVA_IMD_SENSITIVITY,
	  SYS_MSG_SET_DMVA_IMD_PRESENTADJUST,
	  SYS_MSG_SET_DMVA_IMD_PERSONMINWIDTH,
	  SYS_MSG_SET_DMVA_IMD_PERSONMINHEIGHT,
	  SYS_MSG_SET_DMVA_IMD_VEHICLEMINWIDTH,
	  SYS_MSG_SET_DMVA_IMD_VEHICLEMINHEIGHT,
	  SYS_MSG_SET_DMVA_IMD_PERSONMAXWIDTH,
	  SYS_MSG_SET_DMVA_IMD_PERSONMAXHEIGHT,
	  SYS_MSG_SET_DMVA_IMD_VEHICLEMAXWIDTH,
	  SYS_MSG_SET_DMVA_IMD_VEHICLEMAXHEIGHT,
	  SYS_MSG_SET_DMVA_IMD_NUMZONES,
	  SYS_MSG_SET_DMVA_IMD_ZONEENABLE,

  SYS_MSG_SET_DMVA_IMD_ZONE1_ROI_NUMSIDES,
  SYS_MSG_SET_DMVA_IMD_ZONE2_ROI_NUMSIDES,
  SYS_MSG_SET_DMVA_IMD_ZONE3_ROI_NUMSIDES,
  SYS_MSG_SET_DMVA_IMD_ZONE4_ROI_NUMSIDES,

  SYS_MSG_SET_DMVA_IMD_ZONE1_X01,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X02,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X03,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X04,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X05,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X06,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X07,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X08,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X09,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X10,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X11,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X12,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X13,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X14,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X15,
  SYS_MSG_SET_DMVA_IMD_ZONE1_X16,

  SYS_MSG_SET_DMVA_IMD_ZONE1_Y01,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y02,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y03,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y04,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y05,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y06,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y07,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y08,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y09,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y10,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y11,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y12,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y13,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y14,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y15,
  SYS_MSG_SET_DMVA_IMD_ZONE1_Y16,

  SYS_MSG_SET_DMVA_IMD_ZONE2_X01,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X02,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X03,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X04,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X05,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X06,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X07,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X08,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X09,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X10,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X11,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X12,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X13,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X14,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X15,
  SYS_MSG_SET_DMVA_IMD_ZONE2_X16,

  SYS_MSG_SET_DMVA_IMD_ZONE2_Y01,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y02,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y03,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y04,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y05,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y06,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y07,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y08,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y09,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y10,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y11,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y12,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y13,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y14,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y15,
  SYS_MSG_SET_DMVA_IMD_ZONE2_Y16,

  SYS_MSG_SET_DMVA_IMD_ZONE3_X01,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X02,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X03,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X04,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X05,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X06,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X07,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X08,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X09,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X10,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X11,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X12,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X13,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X14,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X15,
  SYS_MSG_SET_DMVA_IMD_ZONE3_X16,

  SYS_MSG_SET_DMVA_IMD_ZONE3_Y01,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y02,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y03,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y04,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y05,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y06,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y07,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y08,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y09,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y10,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y11,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y12,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y13,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y14,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y15,
  SYS_MSG_SET_DMVA_IMD_ZONE3_Y16,

  SYS_MSG_SET_DMVA_IMD_ZONE4_X01,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X02,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X03,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X04,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X05,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X06,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X07,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X08,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X09,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X10,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X11,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X12,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X13,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X14,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X15,
  SYS_MSG_SET_DMVA_IMD_ZONE4_X16,

  SYS_MSG_SET_DMVA_IMD_ZONE4_Y01,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y02,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y03,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y04,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y05,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y06,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y07,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y08,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y09,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y10,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y11,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y12,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y13,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y14,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y15,
  SYS_MSG_SET_DMVA_IMD_ZONE4_Y16,

  SYS_MSG_SET_DMVA_IMD_ZONE1_LABEL,
  SYS_MSG_SET_DMVA_IMD_ZONE2_LABEL,
  SYS_MSG_SET_DMVA_IMD_ZONE3_LABEL,
  SYS_MSG_SET_DMVA_IMD_ZONE4_LABEL,

  SYS_MSG_SET_DMVA_IMD_SAVE,
  SYS_MSG_SET_DMVA_IMD_LOAD,

  /* DMVA Scheduler */
  SYS_MSG_SET_DMVA_SCH_ENABLE,
  SYS_MSG_SET_DMVA_SCH_RULETYPE,
  SYS_MSG_SET_DMVA_SCH_LOADSETTING,
  SYS_MSG_SET_DMVA_SCH_RULELABEL,
  SYS_MSG_SET_DMVA_SCH_STARTDAY,
  SYS_MSG_SET_DMVA_SCH_STARTTIME,
  SYS_MSG_SET_DMVA_SCH_ENDDAY,
  SYS_MSG_SET_DMVA_SCH_ENDTIME,
  SYS_MSG_SET_DMVA_SCH_START,
  SYS_MSG_SET_DMVA_SCH_DELRULE,

  /* DMVA Enc Roi Enable */
  SYS_MSG_SET_DMVA_ENC_ROIENABLE,

	SYS_MSG_SET_SNTP_FQDN, ///< Set SNTP FQDN. //by Larry(128)
	SYS_MSG_RESET_LOG,  ///by Larry(129)
	SYS_MSG_SET_BOA_PROTOCOL, ///by Larry(130)
	SYS_MSG_RESET_TO_DEFAULT, ///by Larry(131)
	SYS_MSG_RESET_TO_DEFAULT_PREPARAT, ///by Larry(132)
	SYS_MSG_CHECK_IP_MODE,    ///by Larry(133)
	SYS_MSG_CHECK_PPPOE_MODE, ///by Larry(134)
	SYS_MSG_CHECK_RTSP_MODE,  ///by Larry(135)
	SYS_MSG_CHECK_FTP_EVEN_MODE, ///by Larry(136)
	SYS_MSG_GET_FTP_RFTPENABLE,  ///by Larry(137)
	SYS_MSG_CHECK_TESTFUNCTION_MODE, //by Larry
	SYS_MSG_CHECK_SEC8021X_MODE,      //by Larry
	SYS_MSG_CHECK_SIP_MODE,           //by Larry
	SYS_MSG_SET_SAMBA_REC_MODE,     		/* Record Media - Dean - 20130530 */
	SYS_MSG_CHECK_SAMBA_REC_MODE,     //by Larry
	SYS_MSG_CHECK_SAMBA_MODE,         //by Larry
	SYS_MSG_CHECK_USB_STATUS,         //by Larry
	SYS_MSG_CHECK_USB_MODE,           //by Larry
	SYS_MSG_CHECK_MMC_STATUS,         //by Larry
	SYS_MSG_CHECK_MMC_MODE,           //by Larry
	SYS_MSG_CHECK_LED_MODE,           //by Larry
	SYS_MSG_CHECK_DDNS_MODE,          //by Larry
	SYS_MSG_CHECK_DIPS_MODE,		/* DIPS_FEATURE - Dean - 20120530 */
	SYS_MSG_GET_UPDATE_MODE,          //by Larry
	SYS_MSG_SET_UPDATE_MODE,          //by Larry
	SYS_MSG_PTZ_GOTO_PRESET,          //by Larry
	SYS_MSG_PTZ_SET_PRESET, 		  //by Larry
	SYS_MSG_SET_PTZ_PATROL,           //by Larry
	SYS_MSG_SET_PTZ_SPEED,            //by Larry
//SYS_MSG_SET_PTZ_MOVE,             //by Larry
	SYS_MSG_SET_PTZ_MOVE,             //by Larry
    SYS_MSG_SET_PTZ_MOVE_ORG,           //Add by Joseph for onvif 2013-03-06
    SYS_MSG_SET_PTZ_STOP,           //Add by Joseph for onvif 2013-08-30
	SYS_MSG_SET_PTZ_MOVETOF,          //by Larry
	SYS_MSG_SET_PTZ_MOVETO,           //by Larry
	SYS_MSG_SET_PTZ_UPDATE,           //by Larry
	SYS_MSG_SET_PTZ_GLOBAL_PATROL,    //by Larry
	SYS_MSG_SET_PTZ_FOCUS,            //by Larry
	SYS_MSG_SET_PTZ_ZOOM,             //by Larry
	SYS_MSG_SET_PTZ_TRACKING,	
	SYS_MSG_SET_PTZ_ROTATE,	
	SYS_MSG_GET_PTZ_SPEED,            //by Larry
	SYS_MSG_GET_PTZ_INFO,             //by Larry
	SYS_MSG_GET_PTZ_POS,				//alice_modify_onvif_code_2011
	SYS_MSG_GET_PTZ_MVStatus,			//alice_modify_onvif_code_2011
	SYS_MSG_GET_PTZ_LIST,             //by Larry
	SYS_MSG_GET_PTZ_LIST2,             //alice_modify_onvif_code_2011
	SYS_MSG_SET_UPDATE_STATUS,        //by Larry
	SYS_MSG_SET_UPNP_MODE,            //by Larry
	SYS_MSG_SET_BONJOUR_MODE,         //by Larry

	SYS_MSG_INIT_WIS_STREAMER,        //by Larry
	SYS_MSG_SET_SNMP_MODE,            //by Larry
	SYS_MSG_SET_QOS_MODE,             //by Larry
	SYS_MSG_SET_COS_MODE,             //by Larry
#if WIFI_FEATURE
	SYS_MSG_GET_NET_CONNECNT,  //alice_modify_2012_5_10_v1
	SYS_MSG_GET_NET_SITESURVEY,  //alice_modify_2012_3_27_v1
	SYS_MSG_GET_NET_SITESURVEYNUM, //alice_modify_2012_3_27_v1
	SYS_MSG_GET_NET_RSSI,//alice_modify_2012_5_10_v1
	SYS_MSG_SET_WIFI_TEST_BEGIN,   	// //alice_modify_2012_5_10_v1
	SYS_MSG_SET_WIFI_WPS,   	// alice_modify_2012_3_15_v1
	SYS_MSG_SET_WIFI_Conf_Data, // alice_modify_2012_3_19_v1
	SYS_MSG_GET_WIFI_NandFlashCN_Data,  // alice_modify_2012_6_29_v1
	SYS_MSG_SET_WIFI_NandFlashCN_Data, // alice_modify_2012_6_29_v1
	SYS_MSG_GET_WIFI_E2P_Data,	//alice_modify_2012_7_13_v1
	SYS_MSG_SET_WIFI_E2P_Data,	//alice_modify_2012_7_13_v1
#endif
#if FOCUS_ZOOM_FEATURE
	SYS_MSG_MOVE_ZOOM_MOTOR,
	SYS_MSG_MOVE_ZOOM,
	SYS_MSG_MOVE_ZOOMIN,
	SYS_MSG_MOVE_ZOOMOUT,
	SYS_MSG_FINETUNE_ZOOMIN,
	SYS_MSG_FINETUNE_ZOOMOUT,
	SYS_MSG_MOVE_FOCUS_MOTOR,
	SYS_MSG_FINETUNE_FOCUSMINUS,
	SYS_MSG_FINETUNE_FOCUSPLUS,
	SYS_MSG_FINETUNE_FOCUSMINUS_1X,
	SYS_MSG_FINETUNE_FOCUSPLUS_1X,
	SYS_MSG_FINETUNE_FOCUSMINUS_2X,
	SYS_MSG_FINETUNE_FOCUSPLUS_2X,
	SYS_MSG_FINETUNE_FOCUSMINUS_3X,
	SYS_MSG_FINETUNE_FOCUSPLUS_3X,
	SYS_MSG_RESET_ZOOM,
	SYS_MSG_RESET_FOCUS,
	SYS_MSG_FULLY_FOCUS_SCAN,
	SYS_MSG_SMART_FOCUS_SCAN,
	SYS_MSG_GET_MOTOR_CUR_POS,
#endif
#if IPNCPTZ_FEATURE
	SYS_MSG_INIT_ZF_CALIBRATE,        //by Larry
	SYS_MSG_INIT_PTZ_DAEMON,          //by Larry
	SYS_MSG_SET_ZOOMTO_MODE,          //by Larry
	SYS_MSG_SET_ZOOMIN_MODE,          //by Larry
	SYS_MSG_SET_ZOOMOUT_MODE,         //by Larry
	SYS_MSG_SET_FOCUSUP_MODE,         //by Larry
	SYS_MSG_SET_FOCUSDOWN_MODE,       //by Larry
	SYS_MSG_SET_FOCUSAUTO_MODE,       //by Larry
	SYS_MSG_CHECK_OVERLAY_MODE,       //by Larry
	SYS_MSG_PTZ_SET_PANSPEED,
	SYS_MSG_PTZ_SET_TILTSPEED,
	SYS_MSG_PTZ_CALIBRATE,
	SYS_MSG_PTZ_SET_DURATION,
#endif
	SYS_MSG_SET_UPDATE_PRESET,        //by Kenny Chiu
	SYS_MSG_SET_UPDATE_PATROL,        //by Kenny Chiu
	SYS_MSG_GET_ZOOM_VALUE,           //by Larry
	SYS_MSG_UPDATE_GPI1,              //by Larry
	SYS_MSG_UPDATE_GPI2,              //by Larry
	SYS_MSG_UPDATE_GPO,               //by Larry
	SYS_MSG_GET_GPI1_STATUS,          //by Larry
	SYS_MSG_GET_GPI2_STATUS,          //by Larry
	SYS_MSG_GET_GPO_STATUS,           //by Larry
	SYS_MSG_SET_AV_PROCESS,           //by Larry
	SYS_MSG_SET_GO_ALARM_DUTATION,    //by Larry
	SYS_MSG_SET_EXTRA_RTSP_MULTI,     //by Larry
	SYS_MSG_SET_PTZ_DEFAULT_HOME,     //by Larry
	SYS_MSG_SET_PTZ_AS_HOME,          //by Larry
	SYS_MSG_GET_PTZ_HOME,             //by Larry
	SYS_MSG_GO_PTZ_HOME,              //by Larry
	SYS_MSG_SET_PTZ_MOVEVIDEO,        //by Larry
	SYS_MSG_SET_PTZ_MOVETOVIDEO,      //by Larry
	SYS_MSG_SET_RESET_BUTTON_TEST,    //by Larry
	SYS_MSG_SET_ECHO_CANCEL_INIT,     //by Larry
	SYS_MSG_SET_ECHO_CANCEL_MIC_VOL,  //by Larry
	SYS_MSG_SET_ECHO_CANCEL_SPK_VOL,  //by Larry
	SYS_MSG_GET_PATROL_LIST,          //by Larry
//SYS_MSG_SET_PATROL_LIST,          //by Larry
//SYS_MSG_ADD_PRESET_LIST,          //by Larry
//SYS_MSG_DEL_PRESET_LIST,          //by Larry
//SYS_MSG_UPDATE_PRESET_LIST,       //by Larry
	SYS_MSG_SET_PORT_MAPPING,         //by Larry
	SYS_MSG_DEL_PORT_MAPPING,         //by Larry
#if IPNC_PELCOD_FEATURE
	SYS_MSG_PELCOD_MOVING,
	SYS_MSG_PELCOD_ADD_PRESET,
	SYS_MSG_PELCOD_DEL_PRESET,
	SYS_MSG_PELCOD_GOTO_PRESET,
	SYS_MSG_PELCOD_SET_HOME,
	SYS_MSG_PELCOD_GO_HOME,
	SYS_MSG_PELCOD_PATROLLING,
	SYS_MSG_RS485_TESTCMD,
#endif	// IPNC_PELCOD_FEATURE
#if IPNC_IRCUT_FEATURE
	SYS_MSG_IRCUT_MODE,
#endif // IPNC_IRCUT_FEATURE
#if Intelligence_FEATURE
	SYS_MSG_OV_ENABLE,
#endif //Intelligence_FEATURE
/* OVERLAY_IMAGE_FEATURE - Dean - 20130709 - Begin */
#if 1//OVERLAY_IMAGE_FEATURE
	SYS_MSG_SET_OVERLAY_IMAGE_CONFIG,
	SYS_MSG_GET_OVERLAY_IMAGE_CONFIG,
#endif // OVERLAY_IMAGE_FEATURE
/* OVERLAY_IMAGE_FEATURE - Dean - 20130709 - End */
/* TAMPER_FEATURE - Dean - 20131007 - Begin */
#if 1 // TAMPER_FEATURE
	SYS_MSG_SET_TAMPER_CONFIG,
	SYS_MSG_GET_TAMPER_CONFIG,
#endif // TAMPER_FEATURE
/* TAMPER_FEATURE - Dean - 20131007 - End */
	SYS_MSG_GET_PORT_USED_LIST,			/* Port Used List CGI - Dean - 20131021 */
	SYS_MSG_START_RESTART_ALL,        //by Larry
	SYS_MSG_STOP_REC,                 //by Larry
	SYS_MSG_SET_TV_OUT,	//Set tvout status of IP netcam ; kenny chiu 20110613
	SYS_MSG_SET_MJPG_STATUS,
	SYS_MSG_SET_RTSP_RESTART,
	SYS_MSG_SET_GPIO_PIN,
	SYS_MSG_SET_GPIO_STATUS,
	SYS_MSG_SET_MPEG41_FRAMERATE_DYNAMIC, // add by kenny chiu 20121025
	SYS_MSG_SET_AEWB_RESET,  // add by kenny chiu 20121210
	//SYS_MSG_SET_MOBILE_FRAMERATE,  // add by kenny chiu 20130426
	//SYS_MSG_SET_MOBILE_RATECONTROL,  // add by kenny chiu 20130426
	//SYS_MSG_SET_MOBILE_QUALITY,  // add by kenny chiu 20130426
	//SYS_MSG_SET_MOBILE_BITRATE,  // add by kenny chiu 20130426
	SYS_MSG_SET_AUTOIRIS_ACTION,  // add by kenny chiu 20130426
	SYS_MSG_SET_AUDIOBROADCASTPORT,
    SYS_MSG_SET_MPEG41_GOP,  //Add by Joseph 20131118
    SYS_MSG_SET_EWDR_MODE,   //Add by Kenny Chiu 20131210
	SYS_MSG_SET_SW_WATCH_DOG_ENABLE,
	SYS_MSG_SET_WDTRST,
	SYS_MSG_SET_EDIMAX_P2P_VALUE,
	SYS_MSG_MAX
};

/**
* @brief Commands used to communicate with file manager.

*/
typedef enum {
	FILE_MSG_QUIT, ///< Let file manager shutdown.
	FILE_MSG_READ, ///< Read system settings from file manager.
	FILE_MSG_WRITE_I, ///< Tell file manager to write system config immediately.
	FILE_MSG_WRITE, ///< Tell file manager to write system config.
	FILE_MSG_FORMAT, ///< Ask file manager to format NAND flash.
	FILE_MSG_RESET, ///< Reset to default.
	FILE_GET_MID, ///< Get file manager's share memory ID.
	FILE_MSG_READ_DMVA_LOG,///< Read DMVA system settings from file manager.
	FILE_MSG_WRITE_DMVATZ,
	FILE_MSG_READ_DMVATZ,
	FILE_MSG_WRITE_DMVAIMD,
	FILE_MSG_READ_DMVAIMD,
    FILE_MSG_WRITE_DMVAOC,
    FILE_MSG_READ_DMVAOC,
    FILE_MSG_WRITE_DMVASMETA,
    FILE_MSG_READ_DMVASMETA,
	FILE_MSG_DMVA_DELETE_INDEX,
	FILE_MSG_DMVA_DELETE_STARTEND_INDEX,
	FILE_MSG_DMVA_DELETE_ALL,
	FILE_MSG_WRITE_DMVA_LOG,
	FILE_MSG_SEARCH_DMVA_EVT,
	FILE_MSG_CLEAR_SYSLOG,
	FILE_MSG_CLEAR_ACCESSLOG,
	FILE_MSG_MAX, ///< File manager command number.
	FILE_LOG_RESET   ///< Reset log file
} FileCmd_t;
/**
* @ingroup MSG_UTIL
* @brief Message type

*/
enum {
	MSG_TYPE_START = 0,

	MSG_TYPE_MSG1, ///< Message type 1. Always reserved for server.
	MSG_TYPE_MSG2, ///< Message type 2.
	MSG_TYPE_MSG3, ///< Message type 3.
	MSG_TYPE_MSG4, ///< Message type 4.
	MSG_TYPE_MSG5, ///< Message type 5.
	MSG_TYPE_MSG6, ///< Message type 6.
	MSG_TYPE_MSG7, ///< Message type 7.
	MSG_TYPE_MSG8, ///< Message type 8.
	MSG_TYPE_MSG9, ///< Message type 9.
	MSG_TYPE_MSG10, ///< Message type 10.
	MSG_TYPE_MSG11, ///< Message type 11.
	MSG_TYPE_MSG12, ///< Message type 12.
	MSG_TYPE_MSG13, ///< Message type 13.
	MSG_TYPE_MSG14, ///< Message type 14.
	MSG_TYPE_MSG15,
	MSG_TYPE_MSG16,//DM365 Specify,RS Adding
	MSG_TYPE_MSG17,//for audio loopback test, by Larry
	MSG_TYPE_MSG18,//for recording log
	MSG_TYPE_MSG19,
	MSG_TYPE_MSG20,
	MSG_TYPE_MSG21,					/* Record Media - Dean - 20130530 */
	MSG_TYPE_END
};

typedef enum {
	FMT_MJPEG = 0,
	FMT_MPEG4,
	FMT_MPEG4_EXT,
	FMT_H264,   //stream3(H264_3)	
	FMT_AUDIO,
	FMT_AUDIO_PCM,
	FMT_MAX_NUM
} FrameFormat_t;

typedef struct _FrameInfo{
	int offset;
	int serial_no;
	int size;
	int width;
	int height;
	int format;
	int frameType;
	int quality;
	int flags;
	unsigned int timestamp;
	unsigned int temporalId;
	int		ref_serial[FMT_MAX_NUM];
}FrameInfo_t;

// IVS_FEATURE
typedef struct _IVS_PARM{
	int option;
	char strings[64];
}IVS_PARM;
// IVS_FEATURE

typedef struct _MSG_MEM{
	unsigned long addr;
	unsigned long size;
}MSG_MEM;

typedef struct _MSG_BUF {
	long 		Des; ///< message type, must be > 0 .
	int 		cmd; ///< data .
	int			Src;
	int			ret;
	MSG_MEM		mem_info;
	FrameInfo_t	frame_info;
#if IVS_FEATURE
	IVS_PARM	ivs_info;	// IVS_FEATURE
#endif
#if PRIVACY_MASK_FEATURE
	PrivacyMaskPrm pm_info;		/* PRIVACY_MASK_FEATURE - Dean - 20130801 */
#endif
#if TAMPER_FEATURE					/* TAMPER_FEATURE - Dean - 20131007 */
	TamperPrm	tamper_info;		/* TAMPER_FEATURE - Dean - 20131007 */
	EventPrm	event_info;			/* TAMPER_FEATURE Event - Dean - 20131007 */
#endif								/* TAMPER_FEATURE - Dean - 20131007 */
	char		extra_data[18];
	PatrolList  patrolist;
	PresetList  prsetlist;
	PTData		ptdata;
	long		NotUse;		/* For sizeof(msgbuf)-sizeof(long) - Dean - 20130530 */
} MSG_BUF;
/**
* @brief System message driver buffer type
*/
typedef struct SYS_MSG_BUF{
	long 		Des; ///< Where this message go. See /ref Sys_Msg_Def.h
	int			cmd; ///< command to control system server.
	int			src; ///< Where this message from. See /ref Sys_Msg_Def.h
	int			shmid; ///< Share memory which was used to communicate with system server.
	int			length; ///< Data length.
	int			offset; ///< Offset to begin of share memory.
} SYS_MSG_BUF;
/**
* @brief File message buffer type

* This structure is used to communicate with file manager.
*/
typedef struct _FILE_MSG_BUF{
	long 		Des; ///< Where this message go.
	FileCmd_t	cmd; ///< Message command ID.
	int			src; ///< Where this message from.
	int			shmid; ///< Share memory ID which is used to communicate.
	int			length; ///< Data length in share memory.
	int			shmidx; ///< Share memory index (0 or 1). 0 is used for system settings; and 1 is used for system log.
	int			nPageNum; ///< System log page number.
	int			nItemNum; ///< System log item number.
} FILE_MSG_BUF;
/**
* @ingroup ALARM_MSG_DRV
* @brief Commands used to communicate with alarm manager.

*/
typedef enum {
	ALARM_EVENT_MOTION_DETECT, ///< Motion detection alarm.
		ALARM_EVENT_DI_1, ///< Motion detection alarm.
		ALARM_EVENT_DI_2, ///< Motion detection alarm.
	ALARM_EVENT_AUDIO_TRIG,
	ALARM_EVENT_MOTION_AUDIO, ///< Motion detection audio alarm.
	ALARM_EVENT_ALARMRESET_TRIG, ///< Reset alarm.
	ALARM_EVENT_ALARMIN_TRIG, ///< External trigger alarm.
	ALARM_EVENT_ALARMETH_TRIG, ///< Ethernet lost alarm.
	ALARM_EVENT_SCHEDULE, ///< Schedule alarm.
	ALARM_EVENT_SCHEDULE_END, ///< Schedule end alarm.
	ALARM_EVENT_QUIT, ///<  Let alarm manager shutdown.
	ALARM_DMVAEVENT_TRIP_ZONE, ///<  DMVA Trip Zone alarm.
	ALARM_EVENT_MAX ///<  Alarm manager command number.
} Event_t;
/**
* @ingroup ALARM_MSG_DRV
* @brief Alarm message buffer type

* This structure is used to communicate with alarm manager.
*/
typedef struct ALARM_MSG_BUF{
	long 		Des; ///< Where this message go.
	int			src; ///< Where this message from.
	Event_t		event; ///< Message command ID.
	int			index; ///< To tell witch schedule is.
	int			serial;///< Motion detect JPEG serial.
	int			alarmaudio_duration;///<Play alarm audio base on duration.
	int			alarmaudio_enable;///<Restart the alarm audio.
} ALARM_MSG_BUF;

/* Record Media - Dean - 20130530 - Begin */
typedef enum {
	SYSTEM_CALL_EVENT_RUN,
	SYSTEM_CALL_EVENT_RESET,
	SYSTEM_CALL_EVENT_QUIT,
	SYSTEM_CALL_EVENT_MAX
} System_Call_Event_t;

typedef struct _SYSTEM_CALL_MSG_BUF{
	long 		Des; ///< Where this message go.
	int			src; ///< Where this message from.
	int			index; ///< To tell witch schedule is.
	System_Call_Event_t		event; ///< Message command ID.
	int			iCmdLen;
	char			strCmd[1024];
	char			reserved[512];
	long			NotUse;		/* For sizeof(msgbuf)-sizeof(long) - Dean - 20130530 */
} SYSTEM_CALL_MSG_BUF;
/* Record Media - Dean - 20130530 - End */

#if WIFI_FEATURE
#define dWifiWPSNoneMode	0
#define dWifiWPSPbcMode		1
#define dWifiWPSPinMode		2
#define dWifiWPSHwPbcMode	3
//alice_modify_2012_3_15_v1
typedef struct
{
	int 	 	WPSRunMode; // 0:none 1:pbc 1:pin 2:hw pbc
	int			GetwifiDatasta;//0:fail 1:get ap data
	int			Mode; //
	char		SSID[128]; ///<
	int			Channel; ///< Where this message from.
	int			Auth; ///< Share memory ID which is used to communicate.
	int			Encr; ///< Data length in share memory.
	char		wpakey[512]; ///< Share memory index (0 or 1). 0 is used for system settings; and 1 is used for system log.
	int 		wepidx;
	int 		weptype;
	char		wepkey[512];

} wifi_wps_data_t;
typedef struct
{
	int			WPSRunMode;
	int			Eth0NetConnect;
}WifiConnectInfo_t;

//alice_modify_2012_3_27_v1
#define RALINK_CONF_FILE		"/etc/Wireless/RT2860STA/RT2860STA.dat"
#define RALINK_CONF_FILE_BAK	"/etc/Wireless/RT2860STA/RT2860STA_bak"
#define RALINK_DEFAULT_FILE2	"/etc/Wireless/RT2860STA/RT2860STA_default2"
#define RALINK_DEFAULT_FILE	"/etc/Wireless/RT2860STA/RT2860STA_default"
#define WIFI_RSSI_FILE	"/tmp/rssi_tmp"
#endif
//alice_modify_2012_3_27_v1

union semwifiun
{
    int val; /* value for SETVAL */
    struct semid_ds *buf; /* buffer for IPC_STAT, IPC_SET */
    unsigned short *array; /* array for GETALL, SETALL */
                           /* Linux specific part: */
    struct seminfo *__buf; /* buffer for IPC_INFO */
};

#define MSG_KEY			0x12345     // av_server key
#define SYS_MSG_KEY		0x36f9      // Message key used by system server.
#define FILE_MSG_KEY	0xc54be5    // File message key.
#define ALARM_KEY		0x542c7ae6  // Alarm message key.
#define AUD_MSG_KEY     0x31        // Audio alarm message key
#define EXTRA_KEY     	0xabcd      // Extra key. 
#define MD_KEY        	0xcdab
#define SYS_CLOSE_KEY	0xdcba
#define SAMBA_KEY     	0xacdb
#define CABLE_INFO_KEY 	0xaabb
#define EXTRA2_KEY      0xabce      //Extra_Info2 struct
#if WIFI_FEATURE
#define WIFI_WPS_INFO_KEY 0x4466FF33 	
#define WIFI_SEM_WIFI_key 0x55FF6611 	
#endif
#define SYSTEM_CALL_KEY	0x6688AA	/* System Call Message Key */
/*
Pre define message usage by function
ex:
FuncName_Msg_Def.h
*/
#include <Stream_Msg_Def.h>
#include <File_Msg_Def.h>
#include <Sys_Msg_Def.h>
#include <Alarm_Msg_Def.h>
//#include <System_Call_Msg_Def.h>			/* Record Media - Dean - 20130530 */
/**
* @ingroup UTILITY API
* @defgroup MSG_QUEUE Message queue.

* This is the place to store message data for communication.
* @{
*/
int Msg_Init( int msgKey );
int Msg_Kill( int qid );
int Msg_Send( int qid, void *pdata , int size );
int Msg_Rsv( int qid, int msg_type, void *pdata , int size );
int Msg_Send_Rsv( int qid, int msg_type, void *pdata , int size );
/** @} */

#define NO_ADV_FTR	0x00
#define FFLAG_VS	0x01
#define FFLAG_LDC	0x02
#define FFLAG_SNF	0x04
#define FFLAG_TNF	0x08

#define VNF_MASK	0x0C
#define VNF_RESET	0x03
#define PREPR_MASK	0x03
#define PREPR_RESET	0x0C

typedef enum{
	ADV_FEATURE_START = 0,

	ADV_FEATURE_VS,
	ADV_FEATURE_LDC,
	ADV_FEATURE_SNF,
	ADV_FEATURE_TNF,
	ADV_FEATURE_FD,

	ADV_FEATURE_END
}ADV_FEATURE_TYPE;
//DM365 Specify,RS
inline static int ADV_FEATURE_GET(ADV_FEATURE_TYPE feature, unsigned int EnMask)
{
	int retval = 0;
	if( feature <= ADV_FEATURE_START || feature >= ADV_FEATURE_END )
		return -1;

	if (((1 << feature) & EnMask))
		retval = 1;
	else
		retval = 0;

	return retval;

}
//DM365 Specify,RS
inline static int ADV_FEATURE_SET(ADV_FEATURE_TYPE feature, int IsEnable, unsigned int *pEnMask)
{
	unsigned int tmpval = 0;

	if (feature <= ADV_FEATURE_START || feature >= ADV_FEATURE_END)
		return -1;

	if (IsEnable)
	{
		tmpval = (1 << feature);
		*pEnMask |= tmpval;

	}
	else
	{
		tmpval = ~(1 << feature);
		*pEnMask &= tmpval;
	}
	return 0;
}
//DM365 Specify,RS
inline static void ADV_FEATURE_CLEAN(unsigned int *pEnMask)
{
	*pEnMask = 0;
}

#if 0
typedef enum{
	FACE_NO_RECOG = 0,
	FACE_RECOGIZE,
	FACE_REGUSER,
	FACE_DELUSER
}FACE_RECOG_TYPE;
#endif

//DM365 Specify,RS
typedef enum{
	FACE_NO_DETECT = 0,
	FACE_DETECT ,
	FACE_MASK ,
	FACE_RECOGIZE,
	FACE_REGUSER,  //ANR
	FACE_DELUSER,  //ANR
	FACE_TYPE_NUM
}FACE_TYPE;
//DM365 Specify,RS
typedef struct _FACE_PARM{
	FACE_TYPE type;
	char strings[16];
}FACE_PARM;


typedef enum{
	DEMO_NONE=0,
	VS_DEMO,
	VNF_DEMO,
	LDC_DEMO,
	FD_DEMO,
	ROI_FD_DEMO,
	ROI_CENTER_DEMO,
	MAX_DEMO_MODE
}ADV_DEMO_ENUM;

typedef enum{
	ROI_NONE = 0,
	ROI_FD_CFG,
	ROI_CENTER_CFG
}ROI_TYPE;

typedef enum{
	SALDRE_SYS_NONE = 0,
	SALDRE_SYS_GLOBAL,
	SALDRE_SYS_LOCAL,
	SALDRE_SYS_ADAPTIVE
} SALDRE_MODE_TYPE;


typedef struct _FaceDetectParam
{
  int	   fdetect; 					    ///< facedetect (ON/OFF)
  int      startX;
  int      startY;
  int      width;
  int      height;
  int      fdconflevel;
  int      fddirection;
  int 	   frecog;
  int	   frconflevel;
  int	   frdatabase;
  int	   pmask;
  int      maskoption;
}FaceDetectParam;

typedef struct _DmvaParam
{
  int	   dmvaenable; 					    ///< dmvaenable (ON/OFF)
  int	   dmvaexptalgoframerate; 		    ///< video (fps/N): 3 means 30/3 = 10 fps
  int	   dmvaexptalgodetectfreq; 		    ///< 10 means once in 10 frames that go to DMVA
  int	   dmvaexptevtrecordenable; 	    ///< 0: Off, 1: On
  int      dmvaexptsmetatrackerenable;      ///< 0: Off, 1: On

}DmvaParam;

typedef struct _DmvaTZParam
{
  /* DMVA TZ parameters */
  int dmvaTZSensitivity; ///< TZ parameters /* 1 to 5: Low to High */
  int dmvaTZPersonMinWidth;///< TZ parameters
  int dmvaTZPersonMinHeight;///< TZ parameters
  int dmvaTZVehicleMinWidth;///< TZ parameters
  int dmvaTZVehicleMinHeight;///< TZ parameters
  int dmvaTZPersonMaxWidth;///< TZ parameters
  int dmvaTZPersonMaxHeight;///< TZ parameters
  int dmvaTZVehicleMaxWidth;///< TZ parameters
  int dmvaTZVehicleMaxHeight;///< TZ parameters
  int dmvaTZDirection; ///< TZ parameters/* 4: Bi-direction, 2: Zone 1 to Zone 2, 1: Zone 2 to Zone 1 */
  int dmvaTZEnable;///< TZ parameters
  int dmvaTZZone1_ROI_numSides;///< TZ parameters
  int dmvaTZZone2_ROI_numSides;///< TZ parameters
  int dmvaTZZone1_x[16];///< TZ parameters
  int dmvaTZZone1_y[16];///< TZ parameters
  int dmvaTZZone2_x[16];///< TZ parameters
  int dmvaTZZone2_y[16];///< TZ parameters
  int dmvaTZPresentAdjust; ///< TZ parameters

}DmvaTZParam;

typedef struct _DmvaMainParam
{
  /* DMVA MAIN PAGE parameters */
  int dmvaCamID;
  int dmvaGetSchedule;
  int dmvaCfgFD;
  int dmvaCfgCTDImdSmetaTzOc; /* Bit 4: OC, Bit 3: TZ, Bit 2: SMETA, Bit 1: IMD, Bit 0: CTD */
  int dmvaDisplayOptions; /* Bit 3: Object Bounding Box, Bit 2: Zones, Bit 1: TimeStamp, Bit 0: MetaData Overlay*/
  int dmvaEventRecordingVAME;/* Bit 3: Video Stream, Bit 2: Audio Stream, Bit 1: MetaData Stream, Bit 0: Event Log */
  int dmvaEventListActionPlaySendSearchTrash;/* Bit 3: Play, Bit 2: Send Email, Bit 1: Search, Bit 0: Trash*/
  int dmvaEventListSelectEvent;
  int dmvaEventListArchiveFlag;
  int dmvaEventListEventType;
  int dmvaEventListStartMonth;
  int dmvaEventListStartDay;
  int dmvaEventListStartTime;
  int dmvaEventListEndMonth;
  int dmvaEventListEndDay;
  int dmvaEventListEndTime;
}DmvaMainParam;

typedef struct _DmvaCTDParam
{
  /* DMVA CTD PAGE parameters */
  int dmvaCfgTDEnv1;/* Detect Lights On to Off */
  int dmvaCfgTDEnv2;/* Detect Lights On to Off */
  int dmvaCfgTDSensitivity;/* 1 to 5: Low to High */
  int dmvaCfgTDResetTime; /* Number of seconds */

}DmvaCTDParam;

typedef struct _DmvaOCParam
{
  /* DMVA OC PAGE parameters */
  int dmvaOCSensitivity; /* 1 to 5: Low to High */
  int dmvaOCObjectWidth;
  int dmvaOCObjectHeight;
  int dmvaOCDirection;/* 4: Bi-direction, 2: Zone 1 to Zone 2, 1: Zone 2 to Zone 1 */
  int dmvaOCEnable;
  int dmvaOCLeftRight;
  int dmvaOCTopBottom;

}DmvaOCParam;

typedef struct _DmvaSMETAParam
{
  /* DMVA SMETA PAGE parameters */
  int dmvaSMETASensitivity; /* 1 to 5: Low to High */
  int dmvaSMETAEnableStreamingData;
  int dmvaSMETAStreamBB;
  int dmvaSMETAStreamVelocity;
  int dmvaSMETAStreamHistogram;
  int dmvaSMETAStreamMoments;

  int dmvaSMETAPresentAdjust; /* 8: Person present, 4: Present vehicle, 2: View Person, 1: View vehicle */
  int dmvaSMETAPersonMinWidth;
  int dmvaSMETAPersonMinHeight;
  int dmvaSMETAVehicleMinWidth;
  int dmvaSMETAVehicleMinHeight;
  int dmvaSMETAPersonMaxWidth;
  int dmvaSMETAPersonMaxHeight;
  int dmvaSMETAVehicleMaxWidth;
  int dmvaSMETAVehicleMaxHeight;
  int dmvaSMETANumZones; /* 1 to 4 */
  int dmvaSMETAZone1_ROI_numSides;///< SMETA parameters
  int dmvaSMETAZone1_x[16];///< SMETA parameters
  int dmvaSMETAZone1_y[16];///< SMETA parameters

}DmvaSMETAParam;

typedef struct _DmvaIMDParam
{
  /* DMVA IMD PAGE parameters */
  int dmvaIMDSensitivity; /* 1 to 5: Low to High */
  int dmvaIMDPresentAdjust; /* 8: Person present, 4: Present vehicle, 2: View Person, 1: View vehicle */
  int dmvaIMDPersonMinWidth;
  int dmvaIMDPersonMinHeight;
  int dmvaIMDVehicleMinWidth;
  int dmvaIMDVehicleMinHeight;
  int dmvaIMDPersonMaxWidth;
  int dmvaIMDPersonMaxHeight;
  int dmvaIMDVehicleMaxWidth;
  int dmvaIMDVehicleMaxHeight;
  int dmvaIMDNumZones; /* 1 to 4 */
  int dmvaIMDZoneEnable; /* Bit 3: Zone 3 enable, Bit 2: Zone 2 enable, Bit 1: Zone 1 enable, Bit 0: Zone 0 enable*/
  int dmvaIMDZone1_ROI_numSides;///< IMD parameters
  int dmvaIMDZone2_ROI_numSides;///< IMD parameters
  int dmvaIMDZone3_ROI_numSides;///< IMD parameters
  int dmvaIMDZone4_ROI_numSides;///< IMD parameters
  int dmvaIMDZone1_x[16];///< IMD parameters
  int dmvaIMDZone1_y[16];///< IMD parameters
  int dmvaIMDZone2_x[16];///< IMD parameters
  int dmvaIMDZone2_y[16];///< IMD parameters
  int dmvaIMDZone3_x[16];///< IMD parameters
  int dmvaIMDZone3_y[16];///< IMD parameters
  int dmvaIMDZone4_x[16];///< IMD parameters
  int dmvaIMDZone4_y[16];///< IMD parameters

}DmvaIMDParam;

typedef struct _ApproMotionPrm{
	int bMotionEnable;
	int bMotionCEnale;
	int MotionLevel;
	int MotionCValue;
	int MotionBlock;
}ApproMotionPrm;

typedef struct _OSDPrm{
	int detailedInfo;
	int	dateEnable;
	int	timeEnable;
	int	logoEnable;
	int logoPos;
	int	textEnable;
	int textPos;
	char text[24];
}OSDPrm;

typedef struct _DateTimePrm{
	int dateFormat;
	int datePos;
	int timeFormat;
	int timePos;
}DateTimePrm;

typedef struct _CodecAdvPrm{
	int ipRatio;
	int fIframe;
	int qpInit;
	int qpMin;
	int qpMax;
	int meConfig;
	int packetSize;
}CodecAdvPrm;

typedef struct _ROI_Prm{
	int startx;
	int starty;
	int width;
	int height;
}ROI_Prm;

typedef struct _CodecROIPrm{
	char 	numROI;
	ROI_Prm	roi[3];
}CodecROIPrm;

typedef struct _DynRangePrm{
	int enable;
	int mode;
	int level;
}DynRangePrm;

typedef struct _VnfParam{
	int enable;
	int mode;
	int strength;
}VnfParam;

/*
typedef struct _OsdTextPrm{
	int nLegnth;
	char strText[16];
}OsdTextPrm;
*/

#if defined (__cplusplus)
}
#endif

#endif

/**
* @page MSG_QUEUE_HOW How to use message queue API?
* 1. Call the API Msg_Init( int msgKey ) to initialize message queue.\n
* 2. Now you can use any message queue API functions as you want.\n
* 3. Call the API Msg_Kill( int qid )  to cleanup message queue.
* @section MSG_QUEUE_HOW_EX Example
* @code
#include <Msg_Def.h>
int main()
{
	int qid, key;
	if((qid=Msg_Init(key)) < 0){
		return -1;
	}
	// More message queue API
	Msg_Kill(qid );
	return 0;
}
* @endcode
*/
