#!/bin/sh
### BEGIN INIT INFO
# Provides:          nvt_server
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: nvt Server startscript.
# Description:       Starts our nvt server
### END INIT INFO
 
# Actions
cd /mnt/vct
case "$1" in
    start)
        # START
	sleep 10
	/mnt/vct/nvt.sh
        ;;
    stop)
        # STOP
	/mnt/vct/killall.sh
        ;;
    restart)
        # RESTART
        ;;
      *)
    echo "Usage: /etc/init.d/nvt {start|stop}"
    exit 1
		
esac
 
exit 0

